config/routes.rb
Handyworks::Application.routes.draw do


  # ORDER is important, the devise routes must appear before any associated
  #       restful route declarations on the same class.
  # Override the Devise::ConfirmationsController
  mount Ckeditor::Engine => '/ckeditor'

  mount StripeEvent::Engine => '/stripe'

  devise_for :users, :controllers => {
    :confirmations => 'confirmations',
    :registrations => 'registrations'
  }
  devise_scope :user do
    put "/confirm" => "confirmations#confirm", :as => :user_confirm
    # this route makes it easier to sign out a current session via either JS or manually with browser location
    #  - otherwise a special _method=delete parameter is required to match the devise default sign out path.
    get "users/sign_out" => "devise/sessions#destroy", :as => :get_destroy_user_session
  end

  scope '/admin' do
    resource :subscription, :only => [:edit, :destroy] do
      put 'update_plan', :to => 'subscriptions#update_plan'
      put 'update_card', :to => 'subscriptions#update_card'
    end
    resource :account, :only => [:edit, :update ] do
      resource :account_setup, :only => [:edit, :update], :path => 'setup'
    end
    # modify path to avoid conflict with devise routes for registration
    resources :users, :path => 'manage_users' do
      resource :permissions, :only => [ :edit, :update ]
      collection do
        get :permissions, :to => "permissions#edit_collection", :as => "edit_permissions"
        put :permissions, :to => "permissions#update_collection", :as => "permissions"
      end
    end
    resources :fee_schedules
    resources :import_groups do
      collection do
        get 'import_status'
      end
    end
    resources :imports
  end

  scope '/setup' do
    resources :providers do
      resource :schedule, :only => [:edit, :update]
    end
    resources :clinics
    resources :schedules, :only => [:show, :update]
    resources :legacy_id_labels, :only => [ :destroy ]
    resources :events, :only => [:create, :update, :destroy]
    resources :procedure_codes
    resources :diagnosis_codes
    resources :third_parties do
      resources :hcfa_form_options, :controller => 'carrier_hcfa_form_options', :except => [ :index ]
    end
    resources :attorneys, :as => :third_parties, :controller => 'third_parties'
    resources :insurance_carriers, :as => :third_parties, :controller => 'third_parties'
    resources :references
  end

  scope '/schedule' do
    resource :calendar, :only => [:show, :edit, :update], :as => "schedule" # has to use a different helper name the appointments calendar paths below
    resources :rooms
    resources :providers, :as => :provider_availability, :only => [:index]
    resources :appointment_types
  end

  scope '/billing' do
    resources :hcfa_form_options, :only => [ :index, :show, :edit, :update, :destroy ]
  end

  scope '/reporting' do
    resources :messages
  end

  scope '/interaction' do
    resources :patients do
      collection do
        get 'letters'
      end
    end
    resource :calendar, :only => [:show, :edit, :update]
  end

  # public appointments
  match '/appts' => 'public_appointments#index', :as => :public_appointments
  match '/appts/:account_id' => 'public_appointments#new', :as => :appointments_by_account
  match '/appts/:account_id/clinics/:clinic_id' => 'public_appointments#new', :as => :appointments_by_clinic
  match '/appts/:account_id/times' => 'public_appointments#times', :as => :appointments_times
  match '/appointments/export_pdf' => 'appointments#export_pdf'
  resource :calendar, :only => [:show, :edit, :update]
  resource :session_settings, :only => [:update]
  resources :appointments, :only => [:new, :show, :create, :update, :destroy]

  resources :subscription_plans, :only => [:index, :show, :create]

  # resources yet to be created
  # match 'patients' => 'home#under_construction', :as => :patients
  match 'cases' => 'home#under_construction', :as => :cases
  match 'transactions' => 'home#under_construction', :as => :transactions
  match 'reports' => 'home#under_construction', :as => :reports
  match 'billing' => 'home#under_construction', :as => :billing

  match 'plans' => 'subscription_plans#index', :as => 'plans'
  match 'news' => 'home#news', :as => 'news'
  match 'news_item' => 'home#news_item', :as => 'news_item'
  match 'contact' => 'home#contact', :as => 'contact'
  match 'features' => 'home#features', :as => 'features'
  match 'faq' => 'home#faq', :as => 'faq'

  get "content/basic"
  get "content/plus"
  get "content/premium"
  get "content/max"
  get "users/show"
  get "subscriptions/create"
  get "providers/getData" => "providers#getData"
  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"

  #-----------------------------------------------------------------------------
  # dynamic routing to return Help information via AJAX requests.
  #   will match 
  #-----------------------------------------------------------------------------
  match 'help(/:label)' => 'helps#get_help', :as => 'get_help'

  #-----------------------------------------------------------------------------
  # field validation 
  #-----------------------------------------------------------------------------
  match 'validate(/:action/(:object(.:format)))' => 'validate#:action', :as => 'validate'

  scope '/mgmt' do
    resources :accounts
    resources :questions
    resources :helps
  end
  post '/contact_us/send_us'
  get '/webhooks/receiver' => 'webhooks#receiver'
  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
  #-----------------------------------------------------------------------------
  # setup the web interface to resque. going to require an app_admin role to
  # access this interface.
  #-----------------------------------------------------------------------------
  namespace :mgmt do
    constraints CanAccessResque do
      mount Resque::Server, :at => "/resque" 
    end
  end
  StripeEvent::Engine.routes.draw do
    post '/webhooks/receiver' => 'webhooks#receiver'
  end
end

app/controllers/appointment_types_controller.rb
class AppointmentTypesController < AuthorizedController
  respond_to :html, :xml, :json
  # GET /appointment_types
  # GET /appointment_types
  def index
    # set by CanCan @appointment_types = AppointmentType.by_account(current_user.account)
    @datatable = AppointmentTypesDatatable.new(view_context,@appointment_types)
    respond_to do |format|
      format.html
      format.json { render :json => @datatable }
    end
  end

  # GET /appointment_types/1
  # GET /appointment_types/1.json
  def show
    # set by CanCan @appointment_type = AppointmentType.find(params[:id])
    respond_with(@appointment_type)
  end

  # GET /appointment_types/new
  # GET /appointment_types/new.json
  def new
    @appointment_type = AppointmentType.new
    @appointment_type.account = current_account
    colour = "#" + "%06x" % (rand * 0xffffff)
    @appointment_types = AppointmentType.where(:account_id => current_account).select('appointment_color')
    while @appointment_types.to_a.map{|x| x.appointment_color}.include?(colour)
      colour = "#" + "%06x" % (rand * 0xffffff)
    end
    @appointment_type.appointment_color = colour
    respond_with(@appointment_type)
  end

  # GET /appointment_types/1/edit
  def edit
    # set by CanCan @appointment_type = AppointmentType.find(params[:id])
    respond_with(@appointment_type)
  end

  # POST /appointment_types
  # POST /appointment_types.json
  def create
    params[:provider_ids] = params[:appointment_type][:provider_ids]
    params[:appointment_type][:provider_ids] = [""]
    @appointment_type = AppointmentType.new(params[:appointment_type])
    if params[:provider_ids] != [""]
      @appointment_type.save
      @appointment_type.provider_ids = params[:provider_ids]
    end
    respond_to do |format|
      if @appointment_type.save
        last_used_new(@appointment_type)
        format.html { redirect_to(appointment_types_path, :notice => 'Appointment type added.') }
        format.json  { head :ok }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @appointment_type.errors, :status => :unprocessable_entity }
        # NOTE: its actually the js format that's being rendered
        #       when called from the editPopup windows, not quite sure why
        format.js { render :json => { :errors => @appointment_type.errors }, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /appointment_types/1
  # PUT /appointment_types/1.json
  def update
    # set by CanCan @appointment_type = AppointmentType.find(params[:id])

    respond_to do |format|
      if @appointment_type.update_attributes(params[:appointment_type])
        format.html { redirect_to(appointment_types_path, :notice => 'Appointment type updated.') }
        format.json  { head :ok }
        # NOTE: if you add a format.js option here the editPopup request would choose that response
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @appointment_type.errors, :status => :unprocessable_entity }
        # NOTE: its actually the js format that's being rendered
        #       when called from the editPopup windows, not quite sure why
        format.js { render :json => { :errors => @appointment_type.errors }, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /appointment_types/1
  # DELETE /appointment_types/1.json
  def destroy
    # set by CanCan @appointment_type = AppointmentType.find(params[:id])
    @appointment_type = AppointmentType.find(params[:id])
    @appointment_type.destroy

    respond_to do |format|
      format.json do
        # BLS this is necessary to avoid a 1-byte respons
        #  - see http://stackoverflow.com/questions/7064127/http-post-head-ok-returning-1-mystery-byte
        render :text => "", :status => :ok
      end
      format.html { redirect_to(appointment_types_path) }
    end
  end
end

app/views/appointment_types/_appointment_type_parameter.html.haml
.number.control-group.optional.input
  %label.control-label.long-label
    = field_label
  .controls
    = f.number_field field_symbol, :maxlength => 5, :style => "width: 40px"

app/views/appointment_types/_appointment_type_property.html.haml
.boolean.control-group.optional.input
  %label.control-label.long-label
    = field_label
  .controls
    = f.check_box field_symbol, :label => '&nbsp;'

app/views/appointment_types/_buttons.html.haml
- button = button_class
.form-buttons
  - unless f.nil?
    = render 'shared/form_buttons_v2', :f => f, :resource_help => 'appointment_types_fb_help', :button => button
  - if params[:action] == "edit"
    - if can? :destroy, @appointment_type
      = render 'shared/delete_button', :path => appointment_type_path(@appointment_type), :target => "appointment_type-#{@appointment_type.id}", :button => button
  - if params[:action] == "show"
    - if can? :update, @appointment_type
      = link_to edit_appointment_type_path(@appointment_type), :class => "#{button}", :title => "Edit" do
        Edit
  -# only display buttons if the request happens to be for a full page view.
  - unless request.xhr?
    -# = render 'shared/switcher', :resource => @appointment_type , :switcher_url => appointment_types_path unless @appointment_type.new_record?
    = link_to appointment_types_path, :class => "#{button}", :title => "Appointment Types" do
      Back

app/views/appointment_types/_form.html.haml
= semantic_form_for @appointment_type, :remote => request.xhr? do |f|
  = render 'buttons', :f => f
  %div.row#top
    %div#col1.span6
      = f.inputs :name => "Public Appointment Options" do
        = f.input :name, :label => 'Describe this Service'
        -#= f.input :description
        = f.input :account_id, :as => :hidden
        = render 'appointment_type_property', f: f, field_label: "Can the public schedule this service?", field_symbol: :is_public
        = render 'appointment_type_property', f: f, field_label: "Can new patients schedule this service?", field_symbol: :for_new_patients
        = render 'appointment_type_property', f: f, field_label: "Can the patient change appointments?", field_symbol: :allow_user_to_change_appointment
        = render 'appointment_type_property', f: f, field_label: "Can the patient cancel appointments?", field_symbol: :allow_user_to_cancel_appointment
        = render 'appointment_type_property', f: f, field_label: "Can the patient delete appointments?", field_symbol: :allow_user_to_delete_appointment
        = render 'appointment_type_property', f: f, field_label: "Auto confirm/book new appointments?", field_symbol: :auto_confirm_appointment_create
        = render 'appointment_type_property', f: f, field_label: "Auto confirm/book changed appointments?", field_symbol: :auto_confirm_appointment_change
        = render 'appointment_type_property', f: f, field_label: "Auto confirm/unbook deleted appointments?", field_symbol: :auto_confirm_appointment_delete
      = f.inputs :name => "Which providers offer this service?" do
        = f.input :providers, :as => :check_boxes, :collection => current_account.providers, :member_label => :signature_name, :wrapper_html => { :class => "no-label" } ,:label => '&nbsp;', :input_html => { :class => "check_boxes" }
      = f.inputs :name => "In which rooms can this service be scheduled?" do
        = f.input :rooms, :as => :check_boxes, :collection => current_account.rooms, :label => '&nbsp;', :input_html => { :class => "check_boxes" }, :wrapper_html => { :class => 'no-label' }
    %div#col2.span6
      = f.inputs :name => "Appointment Scheduling Controls" do
        -# TODO make up help tip
        -# .tip
        -#  = link_to_help 'tip',114, :class => 'field_help icon16 help', :title => "What's this?"
        = render 'appointment_type_parameter', f: f, field_label: "Minimum Duration (minutes)", field_symbol: :duration_min
        = render 'appointment_type_parameter', f: f, field_label: "Typical Duration (minutes)", field_symbol: :duration
        = render 'appointment_type_parameter', f: f, field_label: "Maximum Duration (minutes)", field_symbol: :duration_max
        = render 'appointment_type_parameter', f: f, field_label: "Provider Time (minutes)", field_symbol: :provider_time
        = render 'appointment_type_parameter', f: f, field_label: "Schedule lead time (minutes)", field_symbol: :schedule_lead_time
        = render 'appointment_type_parameter', f: f, field_label: "Pre appointment time (minutes)", field_symbol: :pre_appointment_gap
        = render 'appointment_type_parameter', f: f, field_label: "Post appointment time (minutes)", field_symbol: :post_appointment_gap
        = render 'appointment_type_parameter', f: f, field_label: "New appointment deadline in hours", field_symbol: :can_create_deadline
        = render 'appointment_type_parameter', f: f, field_label: "Change appointment deadline in hours", field_symbol: :can_change_deadline
        = render 'appointment_type_parameter', f: f, field_label: "Cancel appointment deadline in hours", field_symbol: :can_cancel_deadline
        = render 'appointment_type_parameter', f: f, field_label: "Max Advance Appointments", field_symbol: :max_number_of_appointments_user_can_book_in_advance
        .control-group
          = f.label :Color
          .controls
            = f.text_field :appointment_color
          %span.color_picker.icon16.color_picker
        #color_picker

:javascript
  jQuery(function() {
    //#-----------------------------------------------------------------------------
    //# setup the color picker fields, see also HandyworksApp.setupColorPickerHandler
    //#-----------------------------------------------------------------------------
    jQuery("#color_picker").farbtastic("#appointment_type_appointment_color");
    HandyworksApp.appointmentTypeFormValidation("#{@appointment_type.id}","#{@appointment_type.name}");
  });

app/views/appointment_types/destroy.js.haml
-# handles both success and error cases for destroying legacy_id_label
- if @appointment_type.errors.any?
  HandyworksApp.showError("Unable to destroy the appointment type.",".flash");
- else
  HandyworksApp.showSuccess("Appointment type has been removed.",".flash");
  // removes the hidden fee id for this record which Rails puts outside of the row record from fields_for
  $('#appointment_type_#{@appointment_type.id}').remove();

app/views/appointment_types/edit.html.haml
%h3
  Appointment Type: 
  = render 'shared/switcher', :resource => @appointment_type
= render 'form'

app/views/appointment_types/index.html.haml
%table#appointment_types_list.indexTable.display{ :data => { :source => appointment_types_path, :resource => 'appointment_type', :container => 'user_data_content', :collection => 'AppointmentTypes' } }
  %thead
    %tr
      %th
        %div{:style => "width: 50px"}
          - if can? :create, AppointmentType
            = link_to new_appointment_type_path, :class => "icon24 new", :title => "New Appointment Type" do
              &nbsp;
          = link_to_help 'appointment_types_index_help', :class => 'icon24 help', :title => "Help with Appointment Types"  
      %th 
      %th 
      %th
      %th
  %tbody

:javascript
  jQuery(function() {
    //#---------------------------------------------------------------------------
    //# apply the lightbox popup style to editing
    //#---------------------------------------------------------------------------
    HandyworksApp.editPopup(["a.new"], window.document, false);
    //#---------------------------------------------------------------------------
    //# Apply jQuery dataTables to appointment_type list
    //#---------------------------------------------------------------------------
    oTable = HandyworksApp.indexTable(jQuery('#appointment_types_list'),
      #{@datatable.html_as_json.to_json});
  });

app/views/appointment_types/new.html.haml
%h3
  New Appointment Type
= render 'form'

app/views/appointment_types/show.html.haml
%h3
  Appointment Type: 
  = render 'shared/switcher', :resource => @appointment_type
= render 'form'
:javascript
  jQuery(function() {
    HandyworksApp.showViewFormDisable();
  });