config/routes.rb
Handyworks::Application.routes.draw do


  # ORDER is important, the devise routes must appear before any associated
  #       restful route declarations on the same class.
  # Override the Devise::ConfirmationsController
  mount Ckeditor::Engine => '/ckeditor'

  mount StripeEvent::Engine => '/stripe'

  devise_for :users, :controllers => {
    :confirmations => 'confirmations',
    :registrations => 'registrations'
  }
  devise_scope :user do
    put "/confirm" => "confirmations#confirm", :as => :user_confirm
    # this route makes it easier to sign out a current session via either JS or manually with browser location
    #  - otherwise a special _method=delete parameter is required to match the devise default sign out path.
    get "users/sign_out" => "devise/sessions#destroy", :as => :get_destroy_user_session
  end

  scope '/admin' do
    resource :subscription, :only => [:edit, :destroy] do
      put 'update_plan', :to => 'subscriptions#update_plan'
      put 'update_card', :to => 'subscriptions#update_card'
    end
    resource :account, :only => [:edit, :update ] do
      resource :account_setup, :only => [:edit, :update], :path => 'setup'
    end
    # modify path to avoid conflict with devise routes for registration
    resources :users, :path => 'manage_users' do
      resource :permissions, :only => [ :edit, :update ]
      collection do
        get :permissions, :to => "permissions#edit_collection", :as => "edit_permissions"
        put :permissions, :to => "permissions#update_collection", :as => "permissions"
      end
    end
    resources :fee_schedules
    resources :import_groups do
      collection do
        get 'import_status'
      end
    end
    resources :imports
  end

  scope '/setup' do
    resources :providers do
      resource :schedule, :only => [:edit, :update]
    end
    resources :clinics
    resources :schedules, :only => [:show, :update]
    resources :legacy_id_labels, :only => [ :destroy ]
    resources :events, :only => [:create, :update, :destroy]
    resources :procedure_codes
    resources :diagnosis_codes
    resources :third_parties do
      resources :hcfa_form_options, :controller => 'carrier_hcfa_form_options', :except => [ :index ]
    end
    resources :attorneys, :as => :third_parties, :controller => 'third_parties'
    resources :insurance_carriers, :as => :third_parties, :controller => 'third_parties'
    resources :references
  end

  scope '/schedule' do
    resource :calendar, :only => [:show, :edit, :update], :as => "schedule" # has to use a different helper name the appointments calendar paths below
    resources :rooms
    resources :providers, :as => :provider_availability, :only => [:index]
    resources :appointment_types
  end

  scope '/billing' do
    resources :hcfa_form_options, :only => [ :index, :show, :edit, :update, :destroy ]
  end

  scope '/reporting' do
    resources :messages
  end

  scope '/interaction' do
    resources :patients do
      collection do
        get 'letters'
      end
    end
    resource :calendar, :only => [:show, :edit, :update]
  end

  # public appointments
  match '/appts' => 'public_appointments#index', :as => :public_appointments
  match '/appts/:account_id' => 'public_appointments#new', :as => :appointments_by_account
  match '/appts/:account_id/clinics/:clinic_id' => 'public_appointments#new', :as => :appointments_by_clinic
  match '/appts/:account_id/times' => 'public_appointments#times', :as => :appointments_times
  match '/appointments/export_pdf' => 'appointments#export_pdf'
  resource :calendar, :only => [:show, :edit, :update]
  resource :session_settings, :only => [:update]
  resources :appointments, :only => [:new, :show, :create, :update, :destroy]

  resources :subscription_plans, :only => [:index, :show, :create]

  # resources yet to be created
  # match 'patients' => 'home#under_construction', :as => :patients
  match 'cases' => 'home#under_construction', :as => :cases
  match 'transactions' => 'home#under_construction', :as => :transactions
  match 'reports' => 'home#under_construction', :as => :reports
  match 'billing' => 'home#under_construction', :as => :billing

  match 'plans' => 'subscription_plans#index', :as => 'plans'
  match 'news' => 'home#news', :as => 'news'
  match 'news_item' => 'home#news_item', :as => 'news_item'
  match 'contact' => 'home#contact', :as => 'contact'
  match 'features' => 'home#features', :as => 'features'
  match 'faq' => 'home#faq', :as => 'faq'

  get "content/basic"
  get "content/plus"
  get "content/premium"
  get "content/max"
  get "users/show"
  get "subscriptions/create"
  get "providers/getData" => "providers#getData"
  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"

  #-----------------------------------------------------------------------------
  # dynamic routing to return Help information via AJAX requests.
  #   will match 
  #-----------------------------------------------------------------------------
  match 'help(/:label)' => 'helps#get_help', :as => 'get_help'

  #-----------------------------------------------------------------------------
  # field validation 
  #-----------------------------------------------------------------------------
  match 'validate(/:action/(:object(.:format)))' => 'validate#:action', :as => 'validate'

  scope '/mgmt' do
    resources :accounts
    resources :questions
    resources :helps
  end
  post '/contact_us/send_us'
  get '/webhooks/receiver' => 'webhooks#receiver'
  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
  #-----------------------------------------------------------------------------
  # setup the web interface to resque. going to require an app_admin role to
  # access this interface.
  #-----------------------------------------------------------------------------
  namespace :mgmt do
    constraints CanAccessResque do
      mount Resque::Server, :at => "/resque" 
    end
  end
  StripeEvent::Engine.routes.draw do
    post '/webhooks/receiver' => 'webhooks#receiver'
  end
end

app/models/reference.rb
require_dependency 'csv_import'
class Reference < ActiveRecord::Base
  resourcify # add instance method roles
  include CsvImport
  belongs_to :account
  has_one :contact, :as => :contactable, :class_name => 'ContactReference'
  accepts_nested_attributes_for :contact
  validates :account, :presence => true
  
  delegate :company_name, :company_name=, :name, :name=, :to => :contact, :allow_nil => true
  delegate :physical_address_one_liner, :to => :contact, :allow_nil => true
  delegate :state, :to => :contact
  alias_attribute :switcher_title, :company_name
  #-------------------------------------------------------------------------------
  # class methods
  #-------------------------------------------------------------------------------
  scope :alphabetically, :joins => :contact, :order => 'contacts.company_name ASC, contacts.last_name ASC, contacts.first_name ASC'

  def self.by_account(account_id)
    where('account_id = ?', account_id)
  end

  def self.switcher_order(account,clinic)
    by_account(account).alphabetically
  end
  def self.build(configuration={})
    c = self.new(configuration)
    c.contact = ContactReference.build(:contactable => c)
    return c
  end
  #-------------------------------------------------------------------------------
  # instance methods
  #-------------------------------------------------------------------------------
  def can_delete?
    patient_cases.empty? && patients.empty?
  end

  #-------------------------------------------------------------------------------
  # CSV Import
  #-------------------------------------------------------------------------------
  def self.get_csv_instance(import_type,account,row)
    t = Reference.build()
    t.contact.build_fax_phone()
    return t
  end
  def csv_referrer_name
    self.contact.full_name
  end
  def csv_referrer_name=(i_name)
    unless i_name.nil?
      parts = i_name.split(' ')
      if parts.size == 1
        self.contact.last_name = parts[0]
      elsif parts.size == 2
        self.contact.first_name = parts[0]
        self.contact.last_name = parts[1]
      elsif parts.size >= 3
        self.contact.first_name = parts[0]
        self.contact.middle_initial = parts[1]
        self.contact.last_name = parts[2]
      end
    end
  end
end

app/controllers/references_controller.rb
class ReferencesController < AuthorizedController
  respond_to :html, :json, :js
  # GET /references
  # GET /references.json
  def index
    # @references = Reference.all handled by CanCan
    @datatable = ReferencesDatatable.new(view_context,@references)
    respond_to do |format|
      format.html
      format.json { render :json => @datatable }
    end
  end

  # GET /references/1
  # GET /references/1.json
  def show
    # @reference = Reference.find(params[:id]) handled by CanCan
    respond_with(@reference)
  end

  # GET /references/new
  # GET /references/new.json
  def new
    @reference = Reference.build
    @reference.contact.build_business_email
    @reference.contact.build_fax_phone
    @reference.account = current_account
    respond_with(@reference)
  end

  # GET /references/1/edit
  def edit
    # @reference = Reference.find(params[:id]) handled by CanCan
    respond_with(@reference)
  end

  # POST /references
  # POST /references.json
  def create
    @reference = Reference.new(params[:reference])

    respond_to do |format|
      if @reference.save
        last_used_new(@reference)
        format.html { redirect_to(references_path, :notice => 'Referral added.') }
        format.json  { head :ok }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @reference.errors, :status => :unprocessable_entity }
        # NOTE: its actually the js format that's being rendered
        #       when called from the editPopup windows, not quite sure why
        format.js { render :json => { :errors => @reference.errors }, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /references/1
  # PUT /references/1.json
  def update
    # @reference = Reference.find(params[:id]) handled by CanCan

    respond_to do |format|
      if @reference.update_attributes(params[:reference])
        format.html { redirect_to(references_path, :notice => 'Referral updated.') }
        format.json  { head :ok }
        # NOTE: if you add a format.js option here the editPopup request would choose that response
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @reference.errors, :status => :unprocessable_entity }
        # NOTE: its actually the js format that's being rendered
        #       when called from the editPopup windows, not quite sure why
        format.js { render :json => { :errors => @reference.errors }, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    # @reference = Reference.find(params[:id]) handled by CanCan
    @reference.destroy

    respond_to do |format|
      format.json do
        # BLS this is necessary to avoid a 1-byte respons
        #  - see http://stackoverflow.com/questions/7064127/http-post-head-ok-returning-1-mystery-byte
        render :text => "", :status => :ok
      end
      format.html { redirect_to(references_url) }
    end
  end
end

app/views/references/_buttons.html.haml
- button = button_class
.form-buttons
  - unless f.nil?
    = render 'shared/form_buttons_v2', :f => f, :resource_help => 'references_fb_help', :button => button
  - if params[:action] == "edit"
    - if can? :destroy, @reference
      = render 'shared/delete_button', :path => reference_path(@reference), :target => "reference-#{@reference.id}", :button => button
  - if params[:action] == "show"
    - if can? :update, @reference
      = link_to edit_reference_path(@reference), :class => "#{button}", :title => "Edit" do
        Edit

app/views/references/_form.html.haml
= semantic_form_for @reference, :remote => request.xhr? do |f|
  = render 'buttons', :f => f
  %div.row#top
    %div#col1.span6
      = f.inputs :name => "Contact Information" do 
        = f.semantic_fields_for :contact do |contact|
          = contact.input :company_name, :required => true, :label => "Your Code"
          = contact.input :first_name, :required => false
          = contact.input :last_name, :required => false
          = f.input :npi, :label => "NPI - HCFA Box 17b" 
          = contact.semantic_fields_for :physical_address do |pa|
            = render 'shared/address_fields', :f => pa
          = contact.semantic_fields_for :business_email do |be|
            = be.input :email, :required => false
          = contact.semantic_fields_for :business_phone do |bp|
            = render 'shared/phone_fields_v1', :f => bp, :is_required => false
        = f.input :account_id, :as => :hidden

    %div#col2.span6
      = f.inputs :name => "Notes" do 
        = f.input :comment, :label => 'Use this area to record additional information about this referral source.'

:javascript
  jQuery(function() {
    HandyworksApp.referenceFormValidation("#{@reference.id}","#{@reference.contact.company_name}");
  });

app/views/references/edit.html.haml
%h3
  Referral Source:  
  = render 'shared/switcher', :resource =>@reference
= render 'form'

app/views/references/index.html.haml
%table#references_list.indexTable.display{ :data => { :source => references_path, :resource => 'reference', :container => 'user_data_content'} }
  %thead
    %tr
      %th 
        %div{:style => "width: 50px"}
          - if can? :create, Reference
            = link_to new_reference_path, :class => "icon24 new", :title => "New Reference" do
              &nbsp;
          = link_to_help 'references_index_help', :class => 'icon24 help', :title => "What's this?"
      %th
      %th
      %th

  %tbody

:javascript
  jQuery(function() {
    //#---------------------------------------------------------------------------
    //# apply the lightbox popup style to editing
    //#---------------------------------------------------------------------------
    HandyworksApp.editPopup(["a.new"], window.document, false)
    //#---------------------------------------------------------------------------
    //# Apply jQuery dataTables to list
    //#---------------------------------------------------------------------------
    HandyworksApp.indexTable(jQuery('#references_list'),
      #{@datatable.html_as_json.to_json});
  });

app/views/references/new.html.haml
%h3
  = "New Referral Source"
= render 'form'

app/views/references/show.html.haml
%h3
  Referral Source:  
  = render 'shared/switcher', :resource =>@reference
= render 'form'

:javascript
  jQuery(function() {
    HandyworksApp.showViewFormDisable();
  });