config/routes.rb
Handyworks::Application.routes.draw do


  # ORDER is important, the devise routes must appear before any associated
  #       restful route declarations on the same class.
  # Override the Devise::ConfirmationsController
  mount Ckeditor::Engine => '/ckeditor'

  mount StripeEvent::Engine => '/stripe'

  devise_for :users, :controllers => {
    :confirmations => 'confirmations',
    :registrations => 'registrations'
  }
  devise_scope :user do
    put "/confirm" => "confirmations#confirm", :as => :user_confirm
    # this route makes it easier to sign out a current session via either JS or manually with browser location
    #  - otherwise a special _method=delete parameter is required to match the devise default sign out path.
    get "users/sign_out" => "devise/sessions#destroy", :as => :get_destroy_user_session
  end

  scope '/admin' do
    resource :subscription, :only => [:edit, :destroy] do
      put 'update_plan', :to => 'subscriptions#update_plan'
      put 'update_card', :to => 'subscriptions#update_card'
    end
    resource :account, :only => [:edit, :update ] do
      resource :account_setup, :only => [:edit, :update], :path => 'setup'
    end
    # modify path to avoid conflict with devise routes for registration
    resources :users, :path => 'manage_users' do
      resource :permissions, :only => [ :edit, :update ]
      collection do
        get :permissions, :to => "permissions#edit_collection", :as => "edit_permissions"
        put :permissions, :to => "permissions#update_collection", :as => "permissions"
      end
    end
    resources :fee_schedules
    resources :import_groups do
      collection do
        get 'import_status'
      end
    end
    resources :imports
  end

  scope '/setup' do
    resources :providers do
      resource :schedule, :only => [:edit, :update]
    end
    resources :clinics
    resources :schedules, :only => [:show, :update]
    resources :legacy_id_labels, :only => [ :destroy ]
    resources :events, :only => [:create, :update, :destroy]
    resources :procedure_codes
    resources :diagnosis_codes
    resources :third_parties do
      resources :hcfa_form_options, :controller => 'carrier_hcfa_form_options', :except => [ :index ]
    end
    resources :attorneys, :as => :third_parties, :controller => 'third_parties'
    resources :insurance_carriers, :as => :third_parties, :controller => 'third_parties'
    resources :references
  end

  scope '/schedule' do
    resource :calendar, :only => [:show, :edit, :update], :as => "schedule" # has to use a different helper name the appointments calendar paths below
    resources :rooms
    resources :providers, :as => :provider_availability, :only => [:index]
    resources :appointment_types
  end

  scope '/billing' do
    resources :hcfa_form_options, :only => [ :index, :show, :edit, :update, :destroy ]
  end

  scope '/reporting' do
    resources :messages
  end

  scope '/interaction' do
    resources :patients do
      collection do
        get 'letters'
      end
    end
    resource :calendar, :only => [:show, :edit, :update]
  end

  # public appointments
  match '/appts' => 'public_appointments#index', :as => :public_appointments
  match '/appts/:account_id' => 'public_appointments#new', :as => :appointments_by_account
  match '/appts/:account_id/clinics/:clinic_id' => 'public_appointments#new', :as => :appointments_by_clinic
  match '/appts/:account_id/times' => 'public_appointments#times', :as => :appointments_times
  match '/appointments/export_pdf' => 'appointments#export_pdf'
  resource :calendar, :only => [:show, :edit, :update]
  resource :session_settings, :only => [:update]
  resources :appointments, :only => [:new, :show, :create, :update, :destroy]

  resources :subscription_plans, :only => [:index, :show, :create]

  # resources yet to be created
  # match 'patients' => 'home#under_construction', :as => :patients
  match 'cases' => 'home#under_construction', :as => :cases
  match 'transactions' => 'home#under_construction', :as => :transactions
  match 'reports' => 'home#under_construction', :as => :reports
  match 'billing' => 'home#under_construction', :as => :billing

  match 'plans' => 'subscription_plans#index', :as => 'plans'
  match 'news' => 'home#news', :as => 'news'
  match 'news_item' => 'home#news_item', :as => 'news_item'
  match 'contact' => 'home#contact', :as => 'contact'
  match 'features' => 'home#features', :as => 'features'
  match 'faq' => 'home#faq', :as => 'faq'

  get "content/basic"
  get "content/plus"
  get "content/premium"
  get "content/max"
  get "users/show"
  get "subscriptions/create"
  get "providers/getData" => "providers#getData"
  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"

  #-----------------------------------------------------------------------------
  # dynamic routing to return Help information via AJAX requests.
  #   will match 
  #-----------------------------------------------------------------------------
  match 'help(/:label)' => 'helps#get_help', :as => 'get_help'

  #-----------------------------------------------------------------------------
  # field validation 
  #-----------------------------------------------------------------------------
  match 'validate(/:action/(:object(.:format)))' => 'validate#:action', :as => 'validate'

  scope '/mgmt' do
    resources :accounts
    resources :questions
    resources :helps
  end
  post '/contact_us/send_us'
  get '/webhooks/receiver' => 'webhooks#receiver'
  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
  #-----------------------------------------------------------------------------
  # setup the web interface to resque. going to require an app_admin role to
  # access this interface.
  #-----------------------------------------------------------------------------
  namespace :mgmt do
    constraints CanAccessResque do
      mount Resque::Server, :at => "/resque" 
    end
  end
  StripeEvent::Engine.routes.draw do
    post '/webhooks/receiver' => 'webhooks#receiver'
  end
end

app/models/fee_schedule.rb
require_dependency 'csv_import'
class FeeSchedule < ActiveRecord::Base
  resourcify # add instance method roles
  include CsvImport
  #-------------------------------------------------------------------------------
  # associations
  #-------------------------------------------------------------------------------
  belongs_to :account
  has_many :fees, :dependent => :destroy
  has_many :procedure_codes, :through => :fees
  has_many :cases
  #-------------------------------------------------------------------------------
  # validations
  #-------------------------------------------------------------------------------
  validates :account, :presence => true
  validates :label, :presence => true,
    :uniqueness => { :scope => :account_id }
  before_destroy :check_cases
  #-------------------------------------------------------------------------------
  # class methods
  #-------------------------------------------------------------------------------
  #-------------------------------------------------------------------------------
  # scopes
  #-------------------------------------------------------------------------------
  def self.by_account(account_id)
    where(:account_id => account_id)
  end

  def self.ordered
    order("label")
  end

  def self.switcher_order(account, clinic)
    by_account(account.id).ordered
  end

  #-------------------------------------------------------------------------------
  # instance methods
  #-------------------------------------------------------------------------------
  def to_s
    self.label
  end

  # creates an appropriate sized title for the switcher drop down.
  def switcher_title
    st = self.to_s
    st.length > 25 ? st[0..24] + "..." : st
  end
  #-------------------------------------------------------------------------------
  # CSV Import
  #-------------------------------------------------------------------------------
  #-------------------------------------------------------------------------------
  # private methods
  #-------------------------------------------------------------------------------
  private
  def check_cases
    if self.cases.count > 0
  #   TODO identify the patient
  #   errors.add :base, "This fee schedule is currently being used by patient #{self.cases.account}"
      errors[:base] << "This fee schedule is currently being used by a patient"    
      return false
    end
  end
  #-------------------------------------------------------------------------------
  # aliased methods
  #-------------------------------------------------------------------------------
end

app/controllers/fee_schedules_controller.rb
class FeeSchedulesController < AuthorizedController
  respond_to :html, :json, :js

  # GET /fee_schedules
  # GET /fee_schedules.json
  def index
    # set by CanCan @fee_schedules = FeeSchedule.by_account(current_user.account_id).ordered
    @fee_schedules = @fee_schedules.ordered()
    respond_with(@fee_schedules)
  end

  # GET /fee_schedules/1
  # GET /fee_schedules/1.json
  def show
    # set by CanCan @fee_schedule = FeeSchedule.find(params[:id])
    respond_with(@fee_schedlule)
  end

  # GET /fee_schedules/new
  # GET /fee_schedules/new.json
  def new
    @fee_schedule = FeeSchedule.new
    @fee_schedule.account = current_account
    respond_with(@fee_schedule)
  end

  # GET /fee_schedules/1/edit
  def edit
    # set by CanCan @fee_schedule = FeeSchedule.find(params[:id])
  end

  # POST /fee_schedules
  # POST /fee_schedules.json
  def create
    @fee_schedule = FeeSchedule.new(params[:fee_schedule])

    respond_to do |format|
      if @fee_schedule.save
        last_used_new(@fee_schedule)
        format.html { redirect_to(@fee_schedule, :notice => 'Fee schedule added.') }
        format.json  { render :json => @fee_schedule, :status => :created, :location => @fee_schedule }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @fee_schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /fee_schedules/1
  # PUT /fee_schedules/1.json
  def update
    # set by CanCan @fee_schedule = FeeSchedule.find(params[:id])

    respond_to do |format|
      if @fee_schedule.update_attributes(params[:fee_schedule])
        format.html { redirect_to(fee_schedules_path, :notice => 'Fee schedule updated.') }
        format.json  { head :ok }
        # NOTE: if you add a format.js option here the editPopup request would choose that response
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @fee_schedule.errors, :status => :unprocessable_entity }
        # NOTE: its actually the js format that's being rendered
        #       when called from the editPopup windows, not quite sure why
        format.js { render :json => { :errors => @fee_schedule.errors }, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /fee_schedules/1
  # DELETE /fee_schedules/1.json
  def destroy
    # set by CanCan @fee_schedule = FeeSchedule.find(params[:id])
    @fee_schedule.destroy

    respond_to do |format|
      format.json do
        # BLS this is necessary to avoid a 1-byte respons
        #  - see http://stackoverflow.com/questions/7064127/http-post-head-ok-returning-1-mystery-byte
        render :text => "", :status => :ok
      end
      format.html { redirect_to(fee_schedules_path, :notice => 'Fee schedule removed.') }
      format.js
    end
  end
end

app/views/fee_schedules/_buttons.html.haml
- unless f.nil?
  = render 'shared/form_buttons', :f => f
.crud_buttons
  -# only display buttons if the request happens to be for a full page view.
  - unless request.xhr?
    = render 'shared/switcher', :resource => @fee_schedule unless @fee_schedule.new_record?
    = link_to fee_schedules_path, :class => "icon48 back", :title => "List Fee Schedules" do
      &nbsp;
  - if params[:action] == "edit"
    - if can? :destroy, @fee_schedule
      = render 'shared/delete_button', :path => fee_schedule_path(@fee_schedule), :target => "fee_schedule-#{@fee_schedule.id}", :button => button
  - if params[:action] == "show"
    - if can? :update, FeeSchedule
      = link_to edit_fee_schedule_path(@fee_schedule), :class => "icon48 edit", :title => "Edit" do
        &nbsp;

app/views/fee_schedules/_form.html.haml
= semantic_form_for @fee_schedule, :remote => request.xhr? do |f|
  = render 'buttons', :f => f
  = f.inputs :name => "Fee Schedule Info" do 
    = f.input :account_id, :as => :hidden
    = f.input :label, :label => 'Fee Schedule Label'
:javascript
  jQuery(function() {
    HandyworksApp.feeScheduleFormValidation();
  });

app/views/fee_schedules/destroy.js.haml
-# handles both success and error cases for destroying fee_schedule
- if @fee_schedule.errors.any?
  HandyworksApp.showError("Unable to delete the fee schedule.",".flash");
- else
  HandyworksApp.showSuccess("Fee schedule has been removed.",".flash");
  // removes the hidden fee id for this record which Rails puts outside of the row record from fields_for
  $('#fee_schedule_#{@fee_schedule.id}').next('input').remove();
  $('#fee_schedule_#{@fee_schedule.id}').remove();

app/views/fee_schedules/edit.html.haml
%h3
  = "Fee Schedule: + @fee_schedule.label
= render 'form'

app/views/fee_schedules/index.html.haml
.crud_buttons
  - if can? :create, FeeSchedule
    = link_to new_fee_schedule_path, :class => "icon48 new" , :title => "New Fee Schedule" do
      &nbsp;

%h3 Fee Schedules

%table#fee_schedules_list.indexTable.display
  %thead
    %tr
      %th &nbsp;
      %th Label
  %tbody
    - @fee_schedules.each do |fee_schedule|
      %tr.fee_schedule_record
        %td
          - if can? :update, fee_schedule
            = link_to edit_fee_schedule_path(fee_schedule), :class => "icon24 fee_schedule-edit option_link", :title => 'Edit' do
              %nbsp;
          - elsif can? :show, fee_schedule
            = link_to fee_schedule_path(fee_schedule), :class => "icon24 fee_schedule-show option_link", :title => 'Show' do
              &nbsp;
          - if can? :destroy, fee_schedule
            = link_to fee_schedule_path(fee_schedule), :confirm => t('delete_confirmation'), :method => :delete, :class => "icon24 fee_schedule-delete option_link", :title => t('tips.destroy') do
              &nbsp;
        %td
          = fee_schedule.label

:javascript
  jQuery(function() {
    //#---------------------------------------------------------------------------
    //# apply the lightbox popup style to editing
    //#---------------------------------------------------------------------------
    HandyworksApp.editPopup([".fee_schedule-edit.option_link",".fee_schedule-show.option_link"]);

    //#---------------------------------------------------------------------------
    //# Apply jQuery dataTables to Fee schedules list
    //#---------------------------------------------------------------------------
    var oTable = HandyworksApp.indexTable(jQuery('#fee_schedules_list'));
    
  });

app/views/fee_schedules/new.html.haml
%h3 
  = "New Fee Schedule"
= render 'form'

app/views/fee_schedules/show.html.haml
= render 'form'
:javascript
  jQuery(function() {
    HandyworksApp.showViewFormDisable();
  });